<a href="https://colab.research.google.com/github/mukeshveeragoni/COLAB/blob/main/Data_cleaning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np


In [9]:
#Replace NaN with 0
arr = np.array([10, 20, np.nan, 40, 50, np.nan, 70])
print(arr)
arr = np.where(np.isnan(arr), 0, arr)
print(arr)


[10. 20. nan 40. 50. nan 70.]


In [16]:
# Remove duplicate values
a=np.array([5, 10, 10, 15, 20, 20, 25])
print("original array",a)
a=np.unique(a)
print("unique array",a)

original array [ 5 10 10 15 20 20 25]
unique array [ 5 10 15 20 25]


In [17]:
# Replace negative values with absolute values
b=np.array([1, -2, 3, -4, 5, -6])
print("OA" , b)
res=np.abs(b)
print("abs" , res)

OA [ 1 -2  3 -4  5 -6]
abs [1 2 3 4 5 6]


In [20]:
# Convert string array to integer
c=np.array(["10", "20", "30", "40"])
result = c.astype(int)
print(result)
print(result.dtype)

[10 20 30 40]
int64


In [21]:
# Array Creation
d=np.array([10, 20, 30, 40, 50])
print(d)

[10 20 30 40 50]


In [44]:
# Create a 2D array:
e = np.array([[1, 2, 3],
 [4, 5, 6],
 [7, 8, 9]])
print("OA" ,e)

print("first row" , e[0])
print("last row",e[-1,-1])


OA [[1 2 3]
 [4 5 6]
 [7 8 9]]
first row [1 2 3]
last row 9


In [47]:
# Indexing
ind = np.array([5, 10, 15, 20, 25])
print("first element" , ind[0])
print("middle element" , ind[2])
print("last element" , ind[-1])

first element 5
middle element 15
last element 25


In [52]:
# Slicing
s = np.array([2, 4, 6, 8, 10, 12, 14])
print(s[0:3])
print(s[-3:])


[2 4 6]
[10 12 14]


In [57]:
# Replace Negative Values
val = np.array([10, -5, 20, -15, 30])
print(val)
val_res=np.where(val<0 , 0 ,val)
print(val_res)

[ 10  -5  20 -15  30]
[10  0 20  0 30]


In [61]:
# Find Even Numbers
even = np.array([1, 2, 3, 4, 5, 6, 7, 8])
print(even)
even_res=even[even%2==0]
print(even_res)

[1 2 3 4 5 6 7 8]
[2 4 6 8]


In [65]:
missing = np.array([10, 20, np.nan, 40, 50, np.nan, 70])
print("original array",missing)
mis_res=np.where(np.isnan(missing) , 0 , missing)
print("convert to zeros ",mis_res)

original array [10. 20. nan 40. 50. nan 70.]
convert to zeros  [10. 20.  0. 40. 50.  0. 70.]


In [66]:
cal = np.array([10, 20, 30, 40, 50])
res1 = np.mean(cal)
res2 = np.max(cal)
res3 = np.min(cal)
print("mean",res1)
print("max",res2)
print("min",res3)

mean 30.0
max 50
min 10


In [77]:
data = np.array([5, 10, np.nan, 20, np.nan, 30])
print(data)
res_mean=np.nanmean(data)
print(res_mean)

res_nan = np.where(np.isnan(data),res_mean , data)
print(res_nan)

[ 5. 10. nan 20. nan 30.]
16.25
[ 5.   10.   16.25 20.   16.25 30.  ]


In [85]:
mini1 = np.array([12, 45, 67, 89, 23, 56])
res_mini = mini1[mini1>50]
print("Greater Than 50 : " ,res_mini)
res_avg = np.average(mini1)
print("Average : ", res_avg)


Greater Than 50 :  [67 89 56]
Average :  48.666666666666664


In [88]:
odd = np.array([1, 2, 3, 4, 5, 6, 7, 8])
res_odd = odd[odd%2==1]
odd_zero = np.where(odd%2==1 , 0 , odd)

print("Odd Number :",res_odd)
print("Odd Number Replaced with zeros : ",odd_zero)

Odd Number : [1 3 5 7]
Odd Number Replaced with zeros :  [0 2 0 4 0 6 0 8]


In [95]:
values = np.array([10, np.nan, 20, np.nan, 30, np.nan])
count_nan = np.isnan(values).sum()
print("count of np.nan :",count_nan)

count of np.nan : 3


In [106]:
array=np.array([45, 67, 23, 89, 12, 90])
max_arr = max(array)
max_ind = np.argmax(array)
print("max value :",max_arr)
print("index of maximum value :" ,max_ind)


max value : 90
index of maximum value : 5


In [108]:
remove = np.array([10, 55, 70, 25, 90, 40])
val_remove = remove[remove>=50]
print("greater than or equal to 50 :" ,val_remove)

greater than or equal to 50 : [55 70 90]


In [120]:
two_d =np.array([[10, 20, 30],
 [40, 50, 60],
 [70, 80, 90]])
print("2D Array :" , two_d)
# first Row
first_row = two_d[0]
second_row =two_d[1]
last_row =two_d[-1,-1]
print("first Row : ", first_row)
print("second Row : ", second_row)
print("last Row : ", last_row)


2D Array : [[10 20 30]
 [40 50 60]
 [70 80 90]]
first Row :  [10 20 30]
second Row :  [40 50 60]
last Row :  90


In [122]:
row_wise_avg = np.array([[50, 60, 70],
 [80, 90, 100],
 [40, 50, 60]])
print(row_wise_avg)
row_wise_avg_res = np.mean(row_wise_avg, axis=1)
print(row_wise_avg_res)

[[ 50  60  70]
 [ 80  90 100]
 [ 40  50  60]]
[60. 90. 50.]


In [126]:
col = np.array([[1, 2, 3],
 [4, 5, 6],
 [7, 8, 9]])
print(col)
first_col = col[0].sum()
second_col = col[1].sum()
third_col = col[2].sum()
print(first_col , second_col , third_col)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
6 15 24
